### ISSUE TITLE
Fix layoutRequest not Getting Reset Causing Problems w/ onLayoutChildren

### ISSUE THREAD

**Issue by neikist** [BeksOmega/looping-layout#48] opened 2021-01-25 14:56 UTC
* **pixel emulator**:
* **api 27**:
* **0.3.2**:

### :bug: Describe

Scroll position jumping when I scroll and glide loading images.

### :snail: Steps to reproduce

I set horizontal orientation. With Glide load images (onBindViewHolder) and cancel loading with onViewRecycled.
Then while all images was not loaded I see jumps to back while I scrolling items.

**Comment by BeksOmega** [comment] 2021-01-25 22:25
Hello! Thank you for reporing this bug :D But sadly, I was not able to reproduce it :/

Could you please provide some more information about what you're experiencing? For example:
- A gif/video of the behavior occuring
- More detailed steps explaining how to reproduce this with the test activities provided by this repo
- A minimal demo project that repoduces this behavior

Best wishes! --Beka

**Comment by neikist** [comment] 2021-01-26 13:43
[LoopingLayoutManagerJumpsDemo.zip](https://github.com/BeksOmega/looping-layout/files/5873594/LoopingLayoutManagerJumpsDemo.zip)
I create and attach sIimple project which reproduces this problem.

**Comment by BeksOmega** [comment] 2021-01-27 01:56
> [LoopingLayoutManagerJumpsDemo.zip](https://github.com/BeksOmega/looping-layout/files/5873594/LoopingLayoutManagerJumpsDemo.zip)
> I create and attach sIimple project which reproduces this problem.

Thanks for taking the time to create a minimal demo :D I was able to reproduce the issue super easily using this! From my testing it seems like there's some issue with the Glide library or how it's being used. If I don't load any images into the view it works fine, but if I do it breaks.

I'll try to do some more investigating and get back to you! But I'm pretty busy at the moment so I'm not sure how soon that will be :/

**Comment by neikist** [comment] 2021-01-27 06:43
Thanks, it's not very important for me now because I not use this library in production. I tried it only just for fun. With simple LinearLayoutManager this bug was not reproduce, so I hope solution exist.

**Comment by BeksOmega** [comment] 2021-01-27 21:17
Well thank you for reporting the bug even though it's not a blocking issue for you! I know that reporting bugs can be time consuming, especially when you have to create a demo like you did for me. So I really appreciate you taking the time! I definitely want to get a fix in for this :D

**Comment by BeksOmega** [comment] 2021-01-30 18:45
Update: the issue seemes to be caused by Glide causing the RecyclerView to trigger a call to [onLayoutChildren](https://github.com/BeksOmega/looping-layout/blob/bb92728505e4b2f52f9daebe232322f5251d10dc/library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt#L176) call that isn't being handled properly because the [layoutRequest](https://github.com/BeksOmega/looping-layout/blob/bb92728505e4b2f52f9daebe232322f5251d10dc/library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt#L177) isn't getting reset properly.

It seems like it used to get properly reset, but I [removed it](https://github.com/BeksOmega/looping-layout/pull/34#discussion_r379858009) because (I think?) it was causing some issues with scroll tests. My theory is that if we *don't* reset the [scroll strategy](https://github.com/BeksOmega/looping-layout/blob/bb92728505e4b2f52f9daebe232322f5251d10dc/library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt#L1161) (but reset everything else), it should properly support scrolls. However #49 needs to be dealt with first, because the tests are too flakey to be helpful at the moment.

**Comment by BeksOmega** [comment] 2021-02-02 01:30
Fixed via #53

**Closed by BeksOmega** 2021-02-02 01:30 UTC
Labels: bug
